App:
  Url: http://localhost:9999
  Workdir: ./
  # local,production,test
  Env: local
  Mq: redis
  Cluster: true
  Secret: 3123dhwahduwad
Rpc:
  Open: true
  Port: 8888
Etcd:
  Host: [127.0.0.1:2379]
  BasePath: chat
Mysql:
  Database: ws
  Username: root
  Password: 123456
  Port: 3306
  Host: localhost
Redis:
  Addr: localhost:6379
  Auth:
  Db: 0
Http:
  Host: 0.0.0.0
  Port: 9999
File:
  Storage: local
  QiniuAk:
  QiniuSK:
  QiniuUrl:
  QiniuBucket: weilvtest
Wechat:
  MiniProgramAppId:
  MiniProgramAppSecret:
  SubscribeTemplateIdOne:
RabbitMq:
  User: admin
  Password: admin
  Host: localhost
  Port: 5672
